# !/usr/bin/python
# coding=utf-8
"""DCC-agnostic model, capability negotiation and planner for rig INTENT.

A rig converter written as ``source node type -> target construct`` is N x M and
never converges. This engine carries what a rigger MEANT instead: a target
receives a value computed by an operator from some sources. Five fixed record
shapes, an open operator vocabulary, and a planner that decides — from data —
what a given target can actually build.

- :mod:`~pythontk.core_utils.engines.rig_graph.rig_model` is the document
  (:class:`RigGraph`, :class:`RigNode`, :class:`RigRecord`, :class:`RigPolicy`)
  and its validation, including the restricted expression grammar.
- :mod:`~pythontk.core_utils.engines.rig_graph.rig_capability` is what ONE
  target can build (:class:`RigCapability`), generated by a conformance run
  rather than hand-written.
- :mod:`~pythontk.core_utils.engines.rig_graph.rig_plan` resolves the two into
  a pure :class:`PlanResult` — what to build, what to bake, and a
  :class:`ReportEntry` for every loss, emitted by the same code that causes it.
- :mod:`~pythontk.core_utils.engines.rig_graph.rig_verify` measures what was
  built against the source's own samples (:class:`RigVerify`) and takes back
  what diverged, so "transferred" means the same thing in both directions.
- :mod:`~pythontk.core_utils.engines.rig_graph.rig_transfer` is the ONE
  orchestration both bridges run (:class:`RigTransfer`): plan-and-build, verify,
  hand the survivors their channels, report.
- :mod:`~pythontk.core_utils.engines.rig_graph.rig_machinery` is the rule for
  what a BAKED rig leaves behind (:class:`RigMachinery`) — apparatus that drives
  nothing on the far side, named by a producer and dropped by a consumer.

Nothing here reaches a scene. Extraction lives in the source DCC's package and
building in the target's; both speak plain dicts, so the same planner serves
every direction and can run a PRE-FLIGHT with no DCC open at all.

The full specification is ``.claude/RIG_GRAPH_SCHEMA.md``.
"""

# Lazy-loaded via parent package - no explicit imports needed
