# !/usr/bin/python
# coding=utf-8
from pythontk.core_utils.module_resolver import bootstrap_package

__package__ = "pythontk"
__version__ = "0.8.86"

"""Expose toolkit utilities with explicit resolver include maps for clarity."""


DEFAULT_INCLUDE = {
    "audio_utils._audio_utils": "AudioUtils",
    "img_utils._img_utils": "*",
    "img_utils.mask_generator": ["MaskGenerator"],
    "img_utils.exposure_equalizer": ["ExposureEqualizer"],
    "img_utils.image_curator": ["ImageCurator"],
    "file_utils.mesh_cleaner": ["MeshCleaner"],
    "str_utils._str_utils": "*",
    "vid_utils._vid_utils": "*",
    "vid_utils.frame_extractor": ["FrameExtractor", "extract_frames"],
    "file_utils._file_utils": "*",
    "file_utils.metadata": "Metadata",
    "file_utils.mesh_convert._mesh_convert": "MeshConvert",
    "iter_utils._iter_utils": "*",
    "math_utils._math_utils": "*",
    "math_utils.progression": "ProgressionCurves",
    "math_utils.noise": "BandLimitedNoise",
    "math_utils.weights": "Weights",
    "geo_utils.polyline": "Polyline",
    "geo_utils.pointcloud": "PointCloud",
    "geo_utils.rail_surface": "RailSurface",
    # Shots engine — DCC-agnostic shot model core shared by mayatk / blendertk
    "core_utils.engines.shots.shot_model": [
        "ShotStore",
        "ShotBlock",
        "ScenePersistence",
        "StoreEvent",
        "ShotDefined",
        "ShotUpdated",
        "ShotRemoved",
        "ActiveShotChanged",
        "SettingsChanged",
        "BatchComplete",
        "StoreInvalidated",
        "SHOT_PALETTE",
    ],
    "core_utils.engines.shots.shot_plan": [
        "ShotMove",
        "MovePlan",
        "plan_respace",
        "plan_ripple_downstream",
        "plan_ripple_upstream",
        "plan_reorder",
    ],
    "core_utils.engines.shots.shot_detection": [
        "STANDARD_TRANSFORM_ATTRS",
        "cluster_segments_by_gap",
        "boundaries_from_key_entries",
    ],
    # shot_apply's `apply` is deliberately NOT root-registered — same policy as
    # the comment below: generic names stay off the top level (consumers import
    # it via its module path).
    # Shot Manifest engine — pure CSV → shot-plan core (mapping/behaviors are
    # imported via their module path to keep generic names off the top level).
    "core_utils.engines.shots.manifest.manifest_model": [
        "parse_csv",
        "ColumnMap",
        "BuilderStep",
        "BuilderObject",
        "PlannedShot",
        "ObjectStatus",
        "StepStatus",
        "detect_behaviors",
    ],
    "core_utils.engines.shots.manifest.manifest_engine": [
        "ShotManifest",
        "resolve_duration",
    ],
    "core_utils.engines.shots.manifest.range_resolver": [
        "resolve_ranges",
        "prune_to_top_boundaries",
    ],
    # Auto-instancing engine — separated-part clustering core (mayatk / blendertk)
    "core_utils.engines.instancing.assembly_sorter": "AssemblySorter",
    # PBR texture engine — map taxonomy / preparation / packaging
    # (mayatk / blendertk material tools + extapps texture apps)
    "core_utils.engines.textures.map_factory": ["MapFactory"],
    "core_utils.engines.textures.map_registry": "MapRegistry",
    "core_utils.engines.textures.output_template": [
        "OutputSpec",
        "OutputTemplate",
        "OutputTemplates",
    ],
    "core_utils.engines.textures.map_compositor": [
        "MapCompositor",
        "BatchResult",
        "NormalOutputMode",
    ],
    "core_utils.engines.textures.map_optimizer": ["MapOptimizer", "Op"],
    "core_utils.engines.textures.mat_report": ["MatReport"],
    "core_utils._core_utils": "*",
    "core_utils.help_mixin": "HelpMixin",
    "core_utils.symbol_record": "SymbolRecord",
    "core_utils.package_manager": "PackageManager",
    "core_utils.git": "Git",
    "core_utils.class_property": "ClassProperty",
    "core_utils.logging_mixin": ["LoggingMixin", "TableMixin"],
    "core_utils.namespace_handler": "NamespaceHandler",
    "core_utils.namedtuple_container": "NamedTupleContainer",
    "core_utils.color": ["Color", "ColorPair", "Palette"],
    "core_utils.hierarchy_utils.hierarchy_diff": "HierarchyDiff",
    "core_utils.singleton_mixin": "SingletonMixin",
    "core_utils.module_reloader": ["ModuleReloader", "reload_package"],
    "core_utils.execution_monitor._execution_monitor": "ExecutionMonitor",
    "core_utils.qc_log": ["QcLog", "QcGate", "GateError"],
    "core_utils.app_launcher": "AppLauncher",
    "core_utils.app_installer": "AppInstaller",
    "core_utils.app_handoff": [
        "HandoffBridge",
        "ScriptLaunchBridge",
        "ScriptLaunchDeliverer",
        "ScriptLaunchSpec",
        "AppSpec",
        "Deliverer",
        "HandoffRequest",
        "Payload",
    ],
    # Process/log line-stream primitives (composed by the app-specific
    # connection shells in mayatk/blendertk, e.g. SubstanceConnection).
    "core_utils.process_stream": ["OutputStream", "ProcessReader", "LogTailer"],
    "core_utils.user_config": ["UserConfig", "user_config_root"],
    "core_utils.preset_store": [
        "PresetStore",
        "sanitize_preset_name",
        "Codec",
        "JSON_CODEC",
    ],
    "core_utils.schema_spec": [
        "SchemaSpec",
        "spec_field",
        "ValidationResult",
        "SchemaError",
        "FieldDoc",
    ],
    "core_utils.template_set": ["TemplateSet"],
    # Generic task/check pipeline base (shared by mayatk/blendertk scene exporters)
    "core_utils.task_factory": "TaskFactory",
    "core_utils.cli": "CLI",
    # Hierarchy utils
    "core_utils.hierarchy_utils.hierarchy_indexer": "HierarchyIndexer",
    "core_utils.hierarchy_utils.hierarchy_matching": "HierarchyMatching",
    "core_utils.hierarchy_utils.hierarchy_analyzer": [
        "HierarchyDifference",
        "HierarchyAnalyzer",
    ],
    "net_utils.ssh_client": "SSHClient",
    "net_utils.credentials": "Credentials",
    "net_utils._net_utils": "NetUtils",
    "net_utils.rpc.client": "RpcClient",
    "net_utils.rpc.installer": [
        "install_plugin",
        "uninstall_plugin",
        "is_plugin_installed",
    ],
    "net_utils.rpc.job": ["Call", "Result", "run_batch"],
    "str_utils.fuzzy_matcher": "FuzzyMatcher",
    "str_utils.hotkey_utils": "HotkeyUtils",
}


bootstrap_package(globals(), include=DEFAULT_INCLUDE)


__all__ = [
    "CoreUtils",
    "AppLauncher",
    "AppInstaller",
    "HandoffBridge",
    "ScriptLaunchBridge",
    "ScriptLaunchDeliverer",
    "ScriptLaunchSpec",
    "AppSpec",
    "Deliverer",
    "HandoffRequest",
    "Payload",
    "OutputStream",
    "ProcessReader",
    "LogTailer",
    "UserConfig",
    "user_config_root",
    "PresetStore",
    "sanitize_preset_name",
    "Codec",
    "JSON_CODEC",
    "SchemaSpec",
    "spec_field",
    "ValidationResult",
    "SchemaError",
    "FieldDoc",
    "TemplateSet",
    "TaskFactory",
    "HelpMixin",
    "SymbolRecord",
    "LoggingMixin",
    "TableMixin",
    "NamespaceHandler",
    "NamedTupleContainer",
    "SingletonMixin",
    "PackageManager",
    "ClassProperty",
    "HierarchyDiff",
    "ModuleReloader",
    "reload_package",
    "ExecutionMonitor",
    "CLI",
    "SSHClient",
    "Credentials",
    "NetUtils",
    "FileUtils",
    "Metadata",
    "MeshConvert",
    "ImgUtils",
    "MapCompositor",
    "BatchResult",
    "NormalOutputMode",
    "MapOptimizer",
    "MaskGenerator",
    "ExposureEqualizer",
    "ImageCurator",
    "MeshCleaner",
    "FrameExtractor",
    "extract_frames",
    "IterUtils",
    "MathUtils",
    "ProgressionCurves",
    "BandLimitedNoise",
    "Weights",
    "Polyline",
    "PointCloud",
    "RailSurface",
    "AssemblySorter",
    "ShotStore",
    "ShotBlock",
    "ScenePersistence",
    "StoreEvent",
    "ShotDefined",
    "ShotUpdated",
    "ShotRemoved",
    "ActiveShotChanged",
    "SettingsChanged",
    "BatchComplete",
    "StoreInvalidated",
    "SHOT_PALETTE",
    "ShotMove",
    "MovePlan",
    "plan_respace",
    "plan_ripple_downstream",
    "plan_ripple_upstream",
    "plan_reorder",
    "STANDARD_TRANSFORM_ATTRS",
    "cluster_segments_by_gap",
    "boundaries_from_key_entries",
    "parse_csv",
    "ColumnMap",
    "BuilderStep",
    "BuilderObject",
    "PlannedShot",
    "ObjectStatus",
    "StepStatus",
    "detect_behaviors",
    "ShotManifest",
    "resolve_duration",
    "resolve_ranges",
    "prune_to_top_boundaries",
    "StrUtils",
    "FuzzyMatcher",
    "HotkeyUtils",
    "AudioUtils",
    "VidUtils",
    "Color",
    "ColorPair",
    "Palette",
]
# Test: 222117
