/*
  GENERATED by m3trik/scripts/sync_scene_records.py from pythontk's
  SceneRecords -- do not edit; run the script after changing a
  declaration.

  The scene records a deliverable publishes for the glTF runtimes: each
  record's key and schema version, the root-extras key its manifest ships
  under and that manifest's own version -- and, where it is declared, the
  manifest's shape. A feature reads a manifest by these, never by a
  spelling of its own.
*/

/**
 * A scene record a GLB conversion publishes for the glTF runtimes.
 * @typedef {object} WebRecord
 * @property {string} key The record's channel on the `data_export` carrier.
 * @property {number} version The record's schema version.
 * @property {string} webKey The root-extras key its manifest ships under.
 * @property {number} webVersion The manifest's own schema version.
 */

/** `shot_metadata`, published as `animation_web`. @type {Readonly<WebRecord>} */
export const SHOTS = Object.freeze({ key: 'shot_metadata', version: 1, webKey: 'animation_web', webVersion: 1 });
/** `lightmap_metadata`, published as `lightmap_web`. @type {Readonly<WebRecord>} */
export const LIGHTMAPS = Object.freeze({ key: 'lightmap_metadata', version: 1, webKey: 'lightmap_web', webVersion: 1 });
/** `shadow_metadata`, published as `shadow_web`. @type {Readonly<WebRecord>} */
export const SHADOWS = Object.freeze({ key: 'shadow_metadata', version: 2, webKey: 'shadow_web', webVersion: 2 });
/** `articulation`, published as `articulation_web`. @type {Readonly<WebRecord>} */
export const ARTICULATION = Object.freeze({ key: 'articulation', version: 1, webKey: 'articulation_web', webVersion: 1 });

/* ------------ the `ArticulationWeb` manifest, declared in pythontk ------------ */

/**
 * The `extras.articulation_web` manifest: the record's rigs, bound to the
 * file's glTF nodes.
 * @typedef {object} ArticulationWeb
 * @property {number} version The manifest's own schema version (SceneRecords.ARTICULATION.web.version).
 * @property {number} metadata_version The version of the articulation record it was bound from.
 * @property {ArticulationWebRig[]} rigs The rigs whose every joint is in the file.
 */

/**
 * One rig bound to the file: its joints and grabbed parts carry node
 * indices.
 * @typedef {object} ArticulationWebRig
 * @property {string} name The rig's name.
 * @property {ArticulationWebJoint[]} joints Its joints, each after its parent.
 * @property {ArticulationWebGrab[]} grab The parts a hand takes hold of that resolved to a node.
 */

/**
 * A joint bound to the one glTF node carrying its name.
 * @typedef {object} ArticulationWebJoint
 * @property {string} name The joint node's name: the join key to the imported transform.
 * @property {number|null} parent An earlier joint's index, or null for a root (its parent is the rig's space).
 * @property {[number, number, number]} t The rest translate in the parent's space, in the DCC's units.
 * @property {[number, number, number, number]} q The rest rotation (the DCC's joint orient), a quaternion x, y, z, w.
 * @property {'xyz'|'yzx'|'zxy'|'xzy'|'yxz'|'zyx'} rotate_order The order the rotation channels compose in; the first letter applies first.
 * @property {ArticulationChannel[]} channels The channels it turns or slides on, in state order.
 * @property {number} node The joint's glTF node index.
 */

/**
 * One channel a joint turns or slides on, with its limits.
 * @typedef {object} ArticulationChannel
 * @property {'rx'|'ry'|'rz'|'tx'|'ty'|'tz'} channel rx/ry/rz turn about the rest frame's own axes (degrees); tx/ty/tz slide along them (the parent's units).
 * @property {number|null} min The lower limit, or null for none.
 * @property {number|null} max The upper limit, or null for none.
 * @property {number} weight How readily a grab moves this channel against the others (1 = evenly).
 */

/**
 * A grabbed part bound to its glTF node.
 * @typedef {object} ArticulationWebGrab
 * @property {number} node The part's glTF node index: the one of its name under its joint's node.
 * @property {number} joint The index of the joint the part rides.
 * @property {string} name The part's node name, as the record spells it.
 */
